from weecfg.extension import ExtensionInstaller

# Copyright 2023 Ron Haupt
# Distributed under the terms of the GNU Public License (GPLv3)


def loader():
    return BasicInstaller()


class BasicInstaller(ExtensionInstaller):
    def __init__(self):
        super(BasicInstaller, self).__init__(
            version="0.1.0",
            name="weewx-rtn",
            description="Renton weewx skin",
            author="Ron Haupt",
            author_email="ronh256@proton.me",
            config={
                "StdReport": {
                    "RtnReport": {
                        "skin": "weewx-rtn",
                        "enable": "true",
                    }
                }
            },
            files=[
                (
                    "bin/user",
                    [
                        "bin/user/weewx-rtn.py",
                    ],
                ),
                (
                    "skins/weewx-rtn",
                    [
                        "skins/weewx-rtn/index.html.tmpl",
                        # "skins/weewx-rtn/yesterday.html.tmpl",
                        # "skins/weewx-rtn/week.html.tmpl",
                        # "skins/weewx-rtn/month.html.tmpl",
                        # "skins/weewx-rtn/dwd.html.tmpl",
                        # "skins/weewx-rtn/day-archive/day-%Y-%m-%d.html.tmpl",
                        # "skins/weewx-rtn/month-%Y-%m.html.tmpl",
                        # "skins/weewx-rtn/NOAA/NOAA-%Y-%m.txt.tmpl",
                        # "skins/weewx-rtn/year.html.tmpl",
                        # "skins/weewx-rtn/NOAA/NOAA-%Y.txt.tmpl",
                        # "skins/weewx-rtn/year-%Y.html.tmpl",
                        # "skins/weewx-rtn/statistics.html.tmpl",
                        # "skins/weewx-rtn/celestial.html.tmpl",
                        # "skins/weewx-rtn/about.html.tmpl",
                        # "skins/weewx-rtn/externals.html.tmpl",
                        # "skins/weewx-rtn/offline.html.tmpl",
                        "skins/weewx-rtn/manifest.json.tmpl",
                        # "skins/weewx-rtn/icon-192x192.png",
                        # "skins/weewx-rtn/icon-256x256.png",
                        # "skins/weewx-rtn/icon-384x384.png",
                        # "skins/weewx-rtn/icon-512x512.png",
                        "skins/weewx-rtn/skin.conf",
                        # "skins/weewx-rtn/lang/de.conf",
                        # "skins/weewx-rtn/lang/en.conf",
                        # "skins/weewx-rtn/lang/it.conf",
                        "skins/weewx-rtn/service-worker.js",
                        "skins/weewx-rtn/dist/main.css",
                        "skins/weewx-rtn/dist/main.js",
                        'skins/Belchertown/js', ['skins/Belchertown/js/belchertown.js.tmpl',
                                 'skins/Belchertown/js/index.html',
                                 'skins/Belchertown/js/responsive-menu.js'
                                ]
        ),
       ('skins/Belchertown/json', ['skins/Belchertown/json/index.html',
                                   'skins/Belchertown/json/weewx_data.json.tmpl'
                                  ]
        ),
                        # "skins/weewx-rtn/dist/live-updates.js",
                        # "skins/weewx-rtn/dist/assets/IBMPlexMono-Regular.woff2",
                        # "skins/weewx-rtn/dist/assets/IBMPlexMono-Regular.woff",
                        # "skins/weewx-rtn/dist/assets/IBMPlexSans-Regular.woff2",
                        # "skins/weewx-rtn/dist/assets/IBMPlexSans-Regular.woff",
                        # "skins/weewx-rtn/dist/assets/IBMPlexSans-SemiBold.woff2",
                        # "skins/weewx-rtn/dist/assets/IBMPlexSans-SemiBold.woff",
                        # "skins/weewx-rtn/dist/assets/IBMPlexSerif-Regular.woff2",
                        # "skins/weewx-rtn/dist/assets/IBMPlexSerif-Regular.woff",
                        "skins/weewx-rtn/favicon.ico",
                        # "skins/weewx-rtn/plotly-custom-build.min.js",
                        # "skins/weewx-rtn/includes/html-head.inc",
                        # "skins/weewx-rtn/includes/almanac-tile.inc",
                        # "skins/weewx-rtn/includes/almanac-tile-simple.inc",
                        # "skins/weewx-rtn/includes/almanac-moon-detail-tile.inc",
                        # "skins/weewx-rtn/includes/almanac-sun-detail-tile.inc",
                        # "skins/weewx-rtn/includes/combined-diagram-tile.inc",
                        # "skins/weewx-rtn/includes/data-table-tile.inc",
                        # "skins/weewx-rtn/includes/diagram-tile.inc",
                        # "skins/weewx-rtn/includes/diagram-tile-wind-rose.inc",
                        # "skins/weewx-rtn/includes/dwd-warning.inc",
                        # "skins/weewx-rtn/includes/stat-tile.inc",
                        # "skins/weewx-rtn/includes/conditions-table.inc",
                        # "skins/weewx-rtn/includes/climatological-days.inc",
                        # "skins/weewx-rtn/includes/ui-shell.inc",
                        # "skins/weewx-rtn/includes/footer.inc",
                        # "skins/weewx-rtn/includes/body-classic.inc",
                        # "skins/weewx-rtn/includes/body-alternative.inc",
                        # "skins/weewx-rtn/includes/forecast.inc",
                        # "skins/weewx-rtn/includes/forecast-table.inc",
                        # "skins/weewx-rtn/includes/icons/barometer.svg",
                        # "skins/weewx-rtn/includes/pictograms/sun.svg",
                        # "skins/weewx-rtn/includes/pictograms/moon.svg",
                        # "skins/weewx-rtn/includes/icons/battery.svg",
                        # "skins/weewx-rtn/includes/icons/signal.svg",
                        # "skins/weewx-rtn/includes/icons/soil-moist.svg",
                        # "skins/weewx-rtn/includes/icons/soil-temp.svg",
                        # "skins/weewx-rtn/includes/icons/lightning.svg",
                        # "skins/weewx-rtn/includes/icons/noise.svg",
                        # "skins/weewx-rtn/includes/icons/voltage.svg",
                        # "skins/weewx-rtn/includes/icons/forecast.svg",
                        # "skins/weewx-rtn/includes/icons/leaf.svg",
                        # "skins/weewx-rtn/includes/icons/hail.svg",
                        # "skins/weewx-rtn/includes/icons/snow.svg",
                        # "skins/weewx-rtn/includes/icons/snow-depth.svg",
                        # "skins/weewx-rtn/includes/icons/snow-moist.svg",
                        # "skins/weewx-rtn/includes/icons/cloud-base.svg",
                        # "skins/weewx-rtn/includes/icons/dew-point.svg",
                        # "skins/weewx-rtn/includes/icons/et.svg",
                        # "skins/weewx-rtn/includes/icons/app-temp.svg",
                        # "skins/weewx-rtn/includes/icons/heat-index.svg",
                        # "skins/weewx-rtn/includes/icons/humidity.svg",
                        # "skins/weewx-rtn/includes/icons/rain-rate.svg",
                        # "skins/weewx-rtn/includes/icons/rain.svg",
                        # "skins/weewx-rtn/includes/icons/radiation.svg",
                        # "skins/weewx-rtn/includes/icons/temp.svg",
                        # "skins/weewx-rtn/includes/icons/uv.svg",
                        # "skins/weewx-rtn/includes/icons/wind-chill.svg",
                        # "skins/weewx-rtn/includes/icons/wind-run.svg",
                        # "skins/weewx-rtn/includes/icons/wind-direction.svg",
                        # "skins/weewx-rtn/includes/icons/wind-direction.inc",
                        # "skins/weewx-rtn/includes/icons/wind-gust.svg",
                        # "skins/weewx-rtn/includes/icons/wind-speed.svg",
                        # "skins/weewx-rtn/includes/icons/sunrise.svg",
                        # "skins/weewx-rtn/includes/icons/sunset.svg",
                        # "skins/weewx-rtn/includes/icons/moon.svg",
                        # "skins/weewx-rtn/includes/icons/moonrise.svg",
                        # "skins/weewx-rtn/includes/icons/moonset.svg",
                        # "skins/weewx-rtn/includes/icons/github.svg",
                        # "skins/weewx-rtn/includes/icons/mask.svg",
                        # "skins/weewx-rtn/includes/icons/wdc.svg",
                        # "skins/weewx-rtn/includes/icons/forecast/B1.svg",
                        # "skins/weewx-rtn/includes/icons/forecast/B2.svg",
                        # "skins/weewx-rtn/includes/icons/forecast/BK.svg",
                        # "skins/weewx-rtn/includes/icons/forecast/CL.svg",
                        # "skins/weewx-rtn/includes/icons/forecast/FW.svg",
                        # "skins/weewx-rtn/includes/icons/forecast/OV.svg",
                        # "skins/weewx-rtn/includes/icons/forecast/SC.svg",
                        # "skins/weewx-rtn/includes/icons/forecast/rain.svg",
                        # "skins/weewx-rtn/includes/icons/forecast/snow.svg",
                        # "skins/weewx-rtn/includes/icons/forecast/sleet.svg",
                        # "skins/weewx-rtn/includes/icons/forecast/fog.svg",
                        # "skins/weewx-rtn/includes/icons/forecast/haze.svg",
                        # "skins/weewx-rtn/includes/icons/forecast/snow--scattered.svg",
                        # "skins/weewx-rtn/includes/icons/forecast/rain--scattered.svg",
                        # "skins/weewx-rtn/includes/icons/forecast/thunderstorm.svg",
                        # "skins/weewx-rtn/includes/icons/forecast/thunderstorm--scattered.svg",
                    ],
                ),
            ],
        )
